### ISSUE TITLE
A1469 and tvOS8.4.4 no Kobi

### ISSUE THREAD

**Issue by maxdenisov** [NSSpiral/Blackb0x#63]
tried to install manually:
wget http://apt.awkwardtv.org/awkwardtv.pub | apt-key add - /usr/bin/apt-key: line 161: run-parts: command not found
--2021-10-24 04:44:47-- http://apt.awkwardtv.org/awkwardtv.pub
Resolving apt.awkwardtv.org... 155.138.254.229
Connecting to apt.awkwardtv.org|155.138.254.229|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://apt.awkwardtv.org/awkwardtv.pub [following]
--2021-10-24 04:44:48-- https://apt.awkwardtv.org/awkwardtv.pub
Connecting to apt.awkwardtv.org|155.138.254.229|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.
gpg: no valid OpenPGP data found.

reboot not helped

**Comment by turtlenation85** [comment]
hey man have you find a fix yet because im having the same problem.

**Comment by ElliotDark** [comment]
> hey man have you find a fix yet because im having the same problem.

You can try download *.deb package on you PC\mac and sent it with scp. Default `login\password` for ssh on jailbroken apple tv - _root\apline_

**Comment by YanAndrew** [comment]
> > hey man have you find a fix yet because im having the same problem.
> 
> You can try download *.deb package on you PC\mac and sent it with scp. Default `login\password` for ssh on jailbroken apple tv - _root\apline_

Excuse me @ElliotDark Could you kindly point me to a step-by-step instruction on:
1. How to send the *.deb package with SCP.
2. 2. What is SSH & where do I go to login?
3.  Where I can download the *.deb package.

My apologies, but I’m not so advanced with my IT skills so I need all the guidance I can get. Like both @turtlenation85 & @maxdenisov I attempted the Blackb0x jailbreak but I’m not sure if it was successful because there’s no Kodi & no NitoTV. I can no longer try the jailbreak again coz Blackb0x now crashes every time I open it. My ATV (2013) A1469 is running software version 7.8. I can’t find any solution elsewhere.

Appreciate any advice / guidance.

Thank you,
Andrew

**Comment by NSSpiral** [comment]
Newest build should install Kodi automatically again
